---
version: '3'
services:
  web:
    image: nginx:1.13.5-alpine
    ports:
      - "3000:80"
    depends_on:
      - app
    volumes:
      - ./docker/nginx/web/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html
  app:
    image: php:7.1.9-fpm-alpine
    volumes:
      - ./app:/var/www/html
  build-client:
    image: node:8.10.0-alpine
    working_dir: /app
    volumes:
      - '.:/app'
    command:
      - npm
      - run
      - build